### ISSUE TITLE
NHibernate support

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero-forsaken#143]
Module Zero has a Abp.Zero.NHibernate package from the beginning. But actually it never properly worked. I was trying to align it with EF for a few days.

I added FluentMigrator migrations (https://github.com/aspnetboilerplate/module-zero/tree/master/src/Abp.Zero.NHibernate/Zero/FluentMigrator/Migrations), so it's identical with the EF-generated database. No problem here.

Then I started to fix entity mappings (https://github.com/aspnetboilerplate/module-zero/tree/master/src/Abp.Zero.NHibernate/Zero/NHibernate/EntityMappings) which causes problems.

Problems are mostly related to EF - NH differences. Major one is;
- In EntityFramework, we use two properties for a many to one relation: A navigation property and a foreign key property. Example: OrganizationUnit (https://github.com/aspnetboilerplate/module-zero/blob/master/src/Abp.Zero/Organizations/OrganizationUnit.cs). it has a "long ParentId" as foreign key and a "OrganizationUnit Parent" as navigation property. Defining a primitive foreign key is good since we can reach to ParentId directly.
- Same approach does not work for NHibernate. Because it can not map both of foreign key and navigation property together. We should only define a navigation property for NH.

So, for these reasons, I could not properly map same domain objects (entities) to EF and NH.

If anyone can help on these, I want to support NH. If not, I will drop NH support for module zero (which is not already working now).

**Comment by 4nonym0us** [comment]
@hikalkan,
Check this out: http://stackoverflow.com/questions/707708/fluent-nhibernate-how-to-map-the-foreign-key-column-as-a-property . It looks like that It's actually the solution you are looking for.

**Comment by hikalkan** [comment]
Hi @4nonym0us 

Unfortunately, this is not solution to my problem.

public virtual Guid SectorID
{
    get { return Sector.ID; }
}   

is not the solution since it works for NH but not for EF (EF will lazy load it).

Formula solution is very good but I can not set SectorId to change relation. I always should set throught navigation property as I understood.

I actually did not test these, but it seems will not work. But I will test.

**Comment by 4nonym0us** [comment]
Hi @hikalkan ,
What about the snippet you mentioned, It won't work and It's obvious because.
You probably misunderstood me as I was talking about the another snippet mentioned on StackOverflow thread:
```
public class Company {
  public virtual Guid Id { get; set; }
  public virtual Guid? SectorId { get; set; }
  public virtual Sector Sector { get; set; }
}

public class CompanyMap : ClassMap<Company> {
  public CompanyMap() {
    Id(x => x.Id); // Maps to a column named "Id"
    References(x => x.Sector); // Maps to a column named "Sector_id", unless you change the NHibernate default mapping rules.
    Map(x => x.SectorId).Formula("[Sector_id]");
  }    
}
```
The `Company` object has both explicitly defined foreign key and the explicitly defined navigation property (just like all of the domain objects in the ABP). The solution here is the mapping – it shows how to map both FK and NavProp:
```
    References(x => x.Sector); // Maps to a column named "Sector_id", unless you change the NHibernate default mapping rules.
    Map(x => x.SectorId).Formula("[Sector_id]");
```
According to this, we can map every DO in the ABP.NH project so DO would become fully compatitable with NH and EF.

**Comment by hikalkan** [comment]
Thanks @4nonym0us for your clarification. I will try this. I should see if formula is two-way. That means if I set SectorId to a different value, it should not be a problem.

**Comment by 4nonym0us** [comment]
You are welcome. I'm hoping that everything will work fine using `Formula()`-mapping. NH is a great tool and I'm hoping that ABP[Zero] would provide an option with such a great OR/M system.
Let me know the results of your tests or if you have any other problems.

**Comment by sonkey2000** [comment]
Actually,I don't like 
`public virtual Guid? SectorId { get; set; }`
`public virtual Sector Sector { get; set; }`
to design the entity,it‘s confused when i use it.
The only benefit for this design is no need to lazy load the Sector when I use the SectorId.
But in the OO way coding ,there is a few scenes to use SectorId.
Popularly, I code it like this:
`Company company = new Company();`
`company.Sector = sector`
`//set other properties....`
`CompanyRepository.Save(company)`

**Comment by hikalkan** [comment]
I also don't like SectorId thing. NHibernate does it better.

**Comment by aaraya-minolusa** [comment]
Hi @hikalkan I just wanted to follow up on this thread. Has there been any progress made on this front? My company recently purchased ASP.NET Zero and our core database is running SQL 2000, which requires us to use NHibernate instead of Entity Framework to leverage the code-first design of this framework. Just wanted to see how likely full NHibernate support will come to fruition, and if it is already available, what the basic steps would be to configure the ASP.NET Zero web application package to use NHibernate. We are early in development so starting with a blank template is still an option if we are able to use ASP.NET Zero with NHibernate (which depends on Module Zero)

**Comment by hikalkan** [comment]
Hi,

Currently, there are minor problems with NHibernate package as I described.
Doesn't EF support SQL 2000? (SQL 200 is too old :().

This can be an option: 

* Add module zero source code into your project (this will prevent to upgrade it anymore when we release new versions, but it's almost mature and we don't add new features much, you can continue it manually).
* Fix missing NHibernate mappings (not too much).
* Check entities and check to better fit to NHibernate (like the navigation properties and foreign key properties as I described).

The only problem will be the migrations. Before all steps, create database using EF, take a database script as first migration. Then you can continue with FluentMigrator or manual SQL scripts.
