### ISSUE TITLE
Add navigation properties to all entities

### ISSUE THREAD

**Issue by jandic** [aspnetboilerplate/module-zero-forsaken#409]
Hi, 

most tables in database created by ABP framework does not contains foreign keys. This is due to missing navigation properties on most tables. It would be useful to add these navigation properties where missing to ensure integrity at database level.

Thanks,
Pavel

**Comment by hikalkan** [comment]
We don't want to add navigation properties for all foreign keys. Two reasons here:

1. Aggregate pattern says that an Aggrate should only reference to other Aggreate by Id. We haven't implemented that perfectly, but don't want to violate it totally.
2. Adding navigation propert for User, Role and Tenant to an entity (say, Permission) requires to make given entity generic, because User, Role and Tenant entities are abstract.

Instead, we can configure foreign keys in EF model.

This issue is related to https://github.com/aspnetboilerplate/module-zero/issues/328.

**Comment by PtwHub** [comment]
Foreign keys should be visible as such in the database. That is why they exist as types in the database: it is very important to be able to identify these crucial relationships. If they are not defined properly, then it impedes/prohibits diverse levels of database hygiene, management, migration, maintenance. If the foreign key is configured in EF, then it is in the database. 

Correcting this would be a big quality-plus without any downside IMHO.

**Comment by hikalkan** [comment]
@PtwHub I know FKs are important in the database side. You can configure your FKs by overriding OnModelCreating method of your DbContext or inside your db migrations.

**Comment by PtwHub** [comment]
Thanks. We are currently working on this approach... No conclusive results yet.
