### ISSUE TITLE
How do I use the SettingManager to retrieve settings from AbpSettings table?

### ISSUE THREAD

**Issue by langman66** [aspnetboilerplate/module-zero-forsaken#43]
I posted this comment over at boilerplate but thought it might be better to post this here.

https://github.com/aspnetboilerplate/aspnetboilerplate/issues/384

@easyest I see where you mentioned you were using the UserManager here https://github.com/aspnetboilerplate/aspnetboilerplate/issues/310 and that Halil instructed not to use the SettingStore directly and that he said "Probably you did not define or register the setting provider."

https://github.com/aspnetboilerplate/aspnetboilerplate/issues/384

Can you share how you defined a provider to have your SettingManager seeded with data from the AbpSetting table?

Thanks,

Chris

**Comment by hikalkan** [comment]
OK. I will add a sample to module-zero sample project.

**Comment by hikalkan** [comment]
Hi,

I added a setting to sample application: https://github.com/aspnetboilerplate/module-zero/tree/master/sample

First, I defined a setting provider (MySettingProvider) and registered it in PreInitialize method of ModuleZeroSampleProjectApplicationModule. This makes the setting available in the application.

When I run the application, I got the 10 value for "QuestionsDefaultPageSize" setting since this is the default value. But when I insert a row to AbpSettings table:

![sample-setting-value](https://cloud.githubusercontent.com/assets/1210527/6546251/923bc97a-c5b5-11e4-9855-1ca4a45cede8.png)

And then re-run application, I got the 6 value. Note that settings are cached. If you change value in db, you can not see the new value unless you re-start the application.
Normally, we don't change settings in db, SettingManager has methods for that.

I hope this helps.

**Comment by langman66** [comment]
Thank you very much!  Let me pull down latest and give it a try.

**Comment by easyest** [comment]
My problem was simple - I did inherit `SettingsProvider` and create setting definitions, but did not register this provider in `ApplicationModule`. You need to add:
```c#
            Configuration.Settings.Providers.Add<AppSettingProvider>();
```
Where `AppSettingProvider` is the class inherited from `SettingsProvider` and overriding `GetSettingDefinitions`

**Comment by BHARAT703** [comment]
Hi @hikalkan,

I have added one currency setting in my Boilerplate Application, I can retrieve my setting value in client side,  but I am getting only default value for my setting.

now, I tried to access this link to add some seeder, https://github.com/aspnetboilerplate/module-zero/tree/master/sample but it's not working anymore. can you give any example on adding value for newly created setting?

One more thing, as I am following ASP.NET ZERO theme, is there any way I can read or update my tenant settings from client side?

Thanks for this great framework...

**Comment by hikalkan** [comment]
Hi @BHARAT703 

How did you add setting value to database? You have 2 options:

1. Use SettingManager.ChangeSetting... methods.
2. Insert database manually. But this requires an application restart since settings are cached.

> As I am following ASP.NET ZERO theme, is there any way I can read or update my tenant settings from client side?

No direct way, because some settings are not appropriate to set by client. If you really need that, you can easily create an API endpoint to do it.

**Comment by BHARAT703** [comment]
@hikalkan thanks for fast response, I got your point.. I am adding data manually and now it's working because I was not removing cached memory..

**Comment by hikalkan** [comment]
You're welcome. So, I'm closing this.
